language: python
python:
- '3.6'
script:
- cd prometheus/unisight-data-bridge
- python setup.py sdist
deploy:
  provider: releases
  api_key:
    secure: g+XjC/TN8frp/TuKftfHflemll/j6cTcOlSs6bmoFvd9DERrNqP738xbe6IBjeLA0QWTr28qtqtNijDrLWYNqOd5joeKJZw+GNbitYU/8G6KmvA6j3KMT5tgOYeXO0W+V2hZNVPUtVi97Hpqp1RtGKvqy5BPKQ5TpkDMuoi22XUQ/Pe2GBAd+vuzeOYdMG9Ksmi9T6F5YKspjvlWyjvf5MofYv5+J26MoEsMjJsf8Fwo6XPOlT3jPuplDUC0LrZtZsSjScjztvYK3ddIraDzk4NASdfTAYhvKvMnOpM6cDz1x7CI9XJfd32UcMSyJUa3ZtT5iP297NfXIm3EVBdHuMPSVZk/I+rSkCO587khrz+TcbkLyzIZZgQkls8d8suB/YCIbivhl3j3Yfce0cl0cNAf0tEpGBvFGPxdLdH1rm5C1viJ+hwgTJdTJZM6Mc6eWX1sYueKJPB20XhdcLF7+UTREux/HGAaBkK7GK6bdgRfV0PdV6ZBhEuzd/7Qwy6ID+wAbPLZsEda8+Ytd8nXq9wSND+5i5kS0Zw/bOcCl3JURjoMkqjAZ+/u02FfdqU0t5IK0sVSoTc21ldC+D8VPK6TOyc1p/j5MHD+r9ZGNcLRGLtiE4Z3Kvzq7F0+rKRbpQEkQbFu4ViekRVRP8qtbE7kZrBmddiNWd6EXit4ZM4=
  file_glob: true
  file: ./prometheus/unisight-data-bridge/dist/unisight-data-bridge-*.tar.gz
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    repo: UnivaCorporation/unisight-visualizations
    tags: true
