{
 "title": "Univa Grid Engine Cluster",
 "description": "Sample dashboard pulling data from a Univa Grid Engine Backed Unisight Cluster.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "label_values(count_jobr_user,user)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(count_jobr_project,project)"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(server_mem_free,hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "#Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count_nodes" }
   ]
  },
  {
   "title": "Number of Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count_cores" }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "count_mem" }
   ]
  },
  {
   "title": "/scratch capacity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    { "expr": "opt_total" }
   ]
  },
  {
   "title": "/scratch available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    { "expr": "opt_avail" }
   ]
  },
  {
   "title": "np_load_avg",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "cluster_np_load_avg" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "cluster_cpu_load" }
   ]
  },
  {
   "title": "Cluster Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "(slots_in_use/count_cores)" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count_mem_used_byHost/count_mem"
    }
   ]
  },
  {
   "title": "Scratch Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "opt_used/opt_total" }
   ]
  },
  {
   "title": "IOPs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    { "expr": "count_usage_iops" }
   ]
  },
  {
   "title": "Cluster Load / Memory / CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(count_mem_used_byHost/count_mem)*100",
     "legendFormat": "mem"
    },
    { "expr": "(slots_in_use/count_cores)*100", "legendFormat": "load" },
    { "expr": "avg(server_cpu_usage)", "legendFormat": "cpu " }
   ]
  },
  {
   "title": "Jobs per Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jobs_per_queue", "legendFormat": "{{queue_name}}" }
   ]
  },
  {
   "title": "Cluster Nodes Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "server_execd_status{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Jobs Monitoring",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "target": "Jobs_Table", "type": "table" }
   ]
  },
  { "title": "Cluster Usage by Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Jobs Usage by User",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count_jobr_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Jobs Queued by Users",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_jobq_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "I/O Usage by User",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "count_usage_io_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Tasks Running by Users",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasks_running_byuser{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Slots Usage by User",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count_slots_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Memory Usage by User",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_mem_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "vmem Usage by User",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_vmem_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Tasks Queued by Users",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasks_queued_byuser{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "cpu usage by user",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "count_usage_cpu_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "WallClock usage by user",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "count_usage_wallclock_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "IOWait Usage by User",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_iow_user{user=~\"$user\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Cluster Usage by Projects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Jobs per Project",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count_jobr_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Slots per Project",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count_slots_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Jobs Queued by Project",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count_jobq_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Tasks Running by Project",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasks_running_byproject{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Mem Usage by Projects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_mem_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "IOW Usage by Projects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_iow_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Projects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_cpu_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Tasks Running by Project",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasks_queued_byproject{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Wallclock Usage by Projects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "count_usage_wallclock_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "maxvmem Usage by Projects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_maxvmem_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "IO Usage by Projects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_io_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "vmem Usage by Projects",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "count_usage_vmem_project{project=~\"$project\"}",
     "legendFormat": "{{project}}"
    }
   ]
  },
  { "title": "Server Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Mem Free by Servers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "server_mem_free{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Local Scartch Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "server_scratch_used/server_scratch_total{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "server_virtualmem{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "server_cpu_usage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}