apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: SimpleJson
    type: grafana-simple-json-datasource
    access: proxy
    url: http://data-bridge:8001
